apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmauth
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: gmauth
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: gmauth
    spec:
      containers:
      - name: gmauth
        image: ghcr.io/tenenwurcel/gmauth:2.0.1
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: gmauth
  labels:
    app: gmauth
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: gmauth